// ── Genki grammar points by chapter ──────────────────────────────────────────
// Covers Genki I ch.3–12 and Genki II ch.13–23, following the 2nd/3rd edition
// tables of contents (the two editions largely agree for these lessons).
// Used by the Roleplay "Grammar Target" feature.
// Each point: id (stable key sent to/from Claude), name (display),
// jp (short HUD label), note (one-line usage), examples (1–2 short sentences).
const GENKI_GRAMMAR = [
  { chapter: 3, book: 'Genki I', label: 'Making a Date', points: [
    { id: 'masu-present', name: '～ます present', jp: '～ます', note: 'Polite present/future: affirmative ～ます, negative ～ません.', examples: ['毎日日本語を勉強します。', '今日はテレビを見ません。'] },
    { id: 'masen-ka', name: '～ませんか invitation', jp: '～ませんか', note: 'Invite someone to do something — "won\'t you…?"', examples: ['一緒に昼ご飯を食べませんか。'] },
    { id: 'particles-wo-de-ni-e', name: 'Particles を・で・に・へ', jp: 'を/で/に/へ', note: 'Direct object を, place of action で, goal/time に, direction へ.', examples: ['図書館で本を読みます。', '十時にうちへ帰ります。'] },
    { id: 'time-ni', name: 'Time reference ～に', jp: '時間＋に', note: 'に after specific times and days; not after 今日・毎日 etc.', examples: ['日曜日に京都へ行きます。'] },
    { id: 'frequency-adverbs', name: 'Frequency adverbs', jp: '毎日/よく', note: '毎日・よく・ときどき・ぜんぜん(+negative) before the verb.', examples: ['ときどきコーヒーを飲みます。', 'ぜんぜん勉強しません。'] },
  ]},
  { chapter: 4, book: 'Genki I', label: 'The First Date', points: [
    { id: 'arimasu-imasu', name: 'Xがあります／います', jp: 'ある/いる', note: 'Existence: あります for things, います for people and animals.', examples: ['机の上に本があります。', '公園に子供がいます。'] },
    { id: 'location-words', name: 'Location words', jp: '〜の前/となり', note: 'Position with 前・うしろ・となり・上・下・中・近く + の.', examples: ['銀行は図書館のとなりです。'] },
    { id: 'past-desu', name: 'Past tense でした', jp: '〜でした', note: 'Noun/な-adjective past: でした ／ じゃなかったです.', examples: ['昨日は雨でした。'] },
    { id: 'past-masu', name: 'Past tense ～ました', jp: '～ました', note: 'Polite past: ～ました ／ ～ませんでした.', examples: ['週末に映画を見ました。', '朝ご飯を食べませんでした。'] },
    { id: 'mo', name: 'Particle も', jp: 'も', note: '"Also/too" — replaces は・が・を.', examples: ['私も京都に行きました。'] },
    { id: 'duration', name: 'Duration ～時間', jp: '〜時間', note: 'Length of time takes no particle: 七時間寝ました.', examples: ['毎日七時間ぐらい寝ます。'] },
  ]},
  { chapter: 5, book: 'Genki I', label: 'A Trip to Okinawa', points: [
    { id: 'i-adjectives', name: 'い-adjectives', jp: 'い形容詞', note: 'Conjugate: 高い・高くない・高かった・高くなかった.', examples: ['この本はとても面白かったです。'] },
    { id: 'na-adjectives', name: 'な-adjectives', jp: 'な形容詞', note: '静か(な): 静かです・静かじゃないです・静かでした.', examples: ['この町はとても静かです。'] },
    { id: 'suki-kirai', name: '好き(な)／きらい(な)', jp: '好き/きらい', note: 'Like/dislike marks its object with が: Xが好きです.', examples: ['私は海が好きです。'] },
    { id: 'mashou', name: '～ましょう／ましょうか', jp: '～ましょう', note: '"Let\'s…" / "shall we…?"', examples: ['一緒に帰りましょう。', '窓を開けましょうか。'] },
  ]},
  { chapter: 6, book: 'Genki I', label: 'A Day in Robert\'s Life', points: [
    { id: 'te-kudasai', name: '～てください', jp: '～てください', note: 'Polite request with the て-form.', examples: ['もう少しゆっくり話してください。'] },
    { id: 'te-mo-ii', name: '～てもいいです', jp: '～てもいい', note: 'Asking for / giving permission.', examples: ['ここに座ってもいいですか。'] },
    { id: 'te-wa-ikemasen', name: '～てはいけません', jp: '～てはいけません', note: 'Prohibition — "you must not…".', examples: ['ここで写真を撮ってはいけません。'] },
    { id: 'te-linking', name: 'て-form linking actions', jp: '～て、～', note: 'Describe two activities in sequence with て.', examples: ['朝起きて、コーヒーを飲みました。'] },
    { id: 'kara-because', name: '～から (because)', jp: '～から', note: 'Reason + から; the reason comes first.', examples: ['今日は忙しいですから、行きません。'] },
  ]},
  { chapter: 7, book: 'Genki I', label: 'Family Picture', points: [
    { id: 'te-iru', name: '～ている', jp: '～ている', note: 'Action in progress or resulting state.', examples: ['今、雨が降っています。', '兄は結婚しています。'] },
    { id: 'body-description', name: 'Xは Yが + adjective', jp: '〜は〜が', note: 'Describing people: かみが長いです, 目が大きいです.', examples: ['田中さんは目が大きいです。'] },
    { id: 'te-adjective-joining', name: 'Joining adjectives (～くて／～で)', jp: '～くて/～で', note: 'Link adjective/noun descriptions: 安くて、おいしい.', examples: ['この店は安くて、おいしいです。'] },
    { id: 'stem-ni-iku', name: 'Verb stem＋に行く', jp: '〜に行く', note: 'Go somewhere in order to do something.', examples: ['デパートにかばんを買いに行きます。'] },
  ]},
  { chapter: 8, book: 'Genki I', label: 'Barbecue', points: [
    { id: 'short-forms', name: 'Short forms (present)', jp: '普通形', note: 'Plain present for casual speech: 食べる・食べない・高い・静かだ.', examples: ['今日、何する？', 'これ、おいしくない。'] },
    { id: 'to-omoimasu', name: '～と思います', jp: '〜と思う', note: 'Opinion: plain form + と思います.', examples: ['明日は雨が降ると思います。'] },
    { id: 'to-itte-imashita', name: '～と言っていました', jp: '〜と言っていた', note: 'Report what someone said.', examples: ['田中さんは忙しいと言っていました。'] },
    { id: 'naide-kudasai', name: '～ないでください', jp: '～ないでください', note: '"Please don\'t…".', examples: ['ここでたばこを吸わないでください。'] },
    { id: 'no-ga-suki', name: 'Verb＋のが好き／上手', jp: '〜のが好き', note: 'Nominalize a verb with の: 料理するのが好きです.', examples: ['私は写真を撮るのが好きです。'] },
  ]},
  { chapter: 9, book: 'Genki I', label: 'Kabuki', points: [
    { id: 'past-short-forms', name: 'Short forms (past)', jp: '普通形過去', note: 'Plain past for casual speech and quoting: 食べた・行かなかった・高かった.', examples: ['昨日、何食べた？', '映画は面白くなかった。'] },
    { id: 'qualifying-nouns', name: 'Qualifying nouns (relative clauses)', jp: '名詞修飾', note: 'Plain-form sentence before a noun: 昨日買った本.', examples: ['昨日買った本はとても面白いです。'] },
    { id: 'mada-te-imasen', name: 'まだ～ていません', jp: 'まだ〜ていない', note: '"Haven\'t … yet".', examples: ['昼ご飯はまだ食べていません。'] },
  ]},
  { chapter: 10, book: 'Genki I', label: 'Winter Vacation Plans', points: [
    { id: 'comparison-two', name: 'AのほうがBより', jp: '〜のほうが', note: 'Comparing two items.', examples: ['電車のほうがバスより速いです。'] },
    { id: 'comparison-superlative', name: '〜の中で一番', jp: '一番', note: 'Superlative among three or more.', examples: ['果物の中でりんごが一番好きです。'] },
    { id: 'adjective-no', name: 'Adjective＋の', jp: '〜の', note: 'の stands in for a noun: 安いのを買いました.', examples: ['もっと大きいのはありますか。'] },
    { id: 'tsumori', name: '～つもりだ', jp: '〜つもり', note: 'Intention: plain form + つもりです.', examples: ['夏休みに日本へ行くつもりです。'] },
    { id: 'naru', name: '～くなる／～になる', jp: '〜なる', note: '"Become": 寒くなる, 元気になる, 先生になる.', examples: ['最近、暖かくなりましたね。'] },
  ]},
  { chapter: 11, book: 'Genki I', label: 'After the Vacation', points: [
    { id: 'tai', name: '～たい (want to)', jp: '～たい', note: 'Want to do: verb stem + たいです.', examples: ['おいしい寿司が食べたいです。'] },
    { id: 'tari-tari', name: '～たり～たりする', jp: '～たり', note: 'Listing sample activities.', examples: ['週末は映画を見たり、買い物したりしました。'] },
    { id: 'koto-ga-aru', name: '～ことがある (experience)', jp: '〜ことがある', note: 'Past experience: plain past + ことがある.', examples: ['富士山に登ったことがありますか。'] },
    { id: 'ya', name: 'AやB (listing)', jp: '〜や〜', note: 'Non-exhaustive listing — "A and B, among others".', examples: ['京都や奈良に行きました。'] },
  ]},
  { chapter: 12, book: 'Genki I', label: 'Feeling Ill', points: [
    { id: 'n-desu', name: '～んです (explanatory)', jp: '〜んです', note: 'Explaining a situation or asking for an explanation.', examples: ['頭が痛いんです。', 'どうしたんですか。'] },
    { id: 'sugiru', name: '～すぎる', jp: '〜すぎる', note: '"Too much": verb stem / adjective stem + すぎる.', examples: ['昨日は飲みすぎました。', 'この靴は大きすぎます。'] },
    { id: 'hou-ga-ii', name: '～ほうがいいです', jp: '〜ほうがいい', note: 'Advice: plain past + ほうがいい ／ ～ないほうがいい.', examples: ['早く寝たほうがいいですよ。'] },
    { id: 'node', name: '～ので', jp: '〜ので', note: '"Because" — softer and more polite than から.', examples: ['熱があるので、今日は帰ります。'] },
    { id: 'nakereba-ikemasen', name: '～なければいけません', jp: '〜なきゃ', note: 'Obligation: なければいけません ／ なきゃいけません.', examples: ['今日中に宿題をしなければいけません。'] },
    { id: 'deshou', name: '～でしょう', jp: '〜でしょう', note: 'Probability / seeking agreement.', examples: ['明日は晴れるでしょう。'] },
  ]},
  { chapter: 13, book: 'Genki II', label: 'Looking for a Part-time Job', points: [
    { id: 'potential', name: 'Potential form', jp: '可能形', note: '"Can do": 食べられる・行ける・できる; object often takes が.', examples: ['漢字が少し読めます。', '私は泳げません。'] },
    { id: 'shi', name: '～し (listing reasons)', jp: '〜し', note: 'List reasons: plain form + し…し.', examples: ['このアパートは安いし、駅に近いし、いいですね。'] },
    { id: 'sou-looks', name: '～そうです (looks like)', jp: '〜そう(様態)', note: 'Seems/looks from appearance: adjective stem + そう.', examples: ['このケーキはおいしそうです。', '雨が降りそうです。'] },
    { id: 'te-miru', name: '～てみる', jp: '〜てみる', note: '"Try doing" something.', examples: ['この服を着てみてもいいですか。'] },
    { id: 'nara', name: '～なら', jp: '〜なら', note: 'Contextual conditional — "if it\'s X (you mean)".', examples: ['京都なら、秋が一番きれいですよ。'] },
  ]},
  { chapter: 14, book: 'Genki II', label: 'Valentine\'s Day', points: [
    { id: 'hoshii', name: '～がほしい', jp: '〜がほしい', note: 'Want a thing: noun + がほしいです.', examples: ['新しい自転車がほしいです。'] },
    { id: 'kamoshiremasen', name: '～かもしれません', jp: '〜かもしれない', note: '"Maybe/might": plain form + かもしれません.', examples: ['明日は雪が降るかもしれません。'] },
    { id: 'ageru-kureru-morau', name: 'あげる／くれる／もらう', jp: 'あげる/くれる/もらう', note: 'Giving and receiving things — direction matters.', examples: ['友達にプレゼントをあげました。', '母にセーターをもらいました。'] },
    { id: 'tara-dou', name: '～たらどうですか', jp: '〜たらどう', note: 'Suggestion: "why don\'t you…?"', examples: ['先生に聞いたらどうですか。'] },
    { id: 'mo-shika', name: 'number＋も／しか～ない', jp: 'も/しか', note: 'Emphasize "as many as" (も) or "only" (しか + negative).', examples: ['猫を三匹も飼っています。', '百円しかありません。'] },
  ]},
  { chapter: 15, book: 'Genki II', label: 'A Trip to Nagano', points: [
    { id: 'volitional', name: 'Volitional form', jp: '意向形', note: 'Casual "let\'s/shall I": 行こう・食べよう.', examples: ['今度一緒に行こう。'] },
    { id: 'volitional-omou', name: 'Volitional＋と思っています', jp: '〜ようと思う', note: 'Plan/intend to do.', examples: ['卒業したら、日本で働こうと思っています。'] },
    { id: 'te-oku', name: '～ておく', jp: '〜ておく', note: 'Do something in advance / in preparation.', examples: ['旅行の前にホテルを予約しておきます。'] },
    { id: 'sentence-qualify-noun', name: 'Sentences qualifying nouns', jp: '名詞修飾(文)', note: 'Longer relative clauses describing a noun.', examples: ['これは父がくれた時計です。'] },
  ]},
  { chapter: 16, book: 'Genki II', label: 'Lost and Found', points: [
    { id: 'te-ageru-kureru-morau', name: '～てあげる／てくれる／てもらう', jp: '〜てくれる等', note: 'Doing favors for / receiving favors from someone.', examples: ['友達が宿題を手伝ってくれました。', '妹に駅まで送ってもらいました。'] },
    { id: 'te-itadakemasenka', name: '～ていただけませんか', jp: '〜ていただけませんか', note: 'Very polite request.', examples: ['もう少しゆっくり話していただけませんか。'] },
    { id: 'to-ii', name: '～といいですね／んですが', jp: '〜といい', note: 'Hopes: "it would be nice if…".', examples: ['明日晴れるといいですね。'] },
    { id: 'toki', name: '～時', jp: '〜時', note: '"When X, Y" — clause tense shows the order of events.', examples: ['日本に行った時、着物を買いました。', '寂しい時、友達に電話します。'] },
    { id: 'te-sumimasen', name: '～てすみませんでした', jp: '〜てすみません', note: 'Apologize for having done something.', examples: ['遅れてすみませんでした。'] },
  ]},
  { chapter: 17, book: 'Genki II', label: 'Grumble and Gossip', points: [
    { id: 'sou-hearsay', name: '～そうです (hearsay)', jp: '〜そう(伝聞)', note: '"I hear that…": plain form + そうです.', examples: ['田中さんは来月結婚するそうです。'] },
    { id: 'tte', name: '～って (casual quote)', jp: '〜って', note: 'Casual version of と／というのは.', examples: ['明日は休みだって。'] },
    { id: 'tara', name: '～たら conditional', jp: '〜たら', note: '"If/when X, Y".', examples: ['お金があったら、旅行したいです。', '駅に着いたら、電話してください。'] },
    { id: 'nakutemo-ii', name: '～なくてもいいです', jp: '〜なくてもいい', note: '"Don\'t have to…".', examples: ['明日は来なくてもいいですよ。'] },
    { id: 'mitai', name: '～みたいです', jp: '〜みたい', note: '"It looks like / apparently / like X".', examples: ['彼は疲れているみたいです。'] },
    { id: 'mae-ni-te-kara', name: '～前に／～てから', jp: '前に/〜てから', note: '"Before doing" / "after doing".', examples: ['寝る前に本を読みます。', '宿題をしてから、遊びに行きます。'] },
  ]},
  { chapter: 18, book: 'Genki II', label: 'John\'s Part-time Job', points: [
    { id: 'transitive-intransitive', name: 'Transitive／intransitive pairs', jp: '自他動詞', note: '開ける/開く, つける/つく — agent acts vs. thing happens.', examples: ['窓を開けました。', '窓が開いています。'] },
    { id: 'te-shimau', name: '～てしまう', jp: '〜てしまう', note: 'Finish completely, or regret (casual 〜ちゃう).', examples: ['宿題を全部やってしまいました。', '財布を忘れてしまいました。'] },
    { id: 'to-conditional', name: '～と conditional', jp: '〜と', note: 'Automatic result: "whenever X, Y".', examples: ['このボタンを押すと、ドアが開きます。'] },
    { id: 'nagara', name: '～ながら', jp: '〜ながら', note: 'Doing two things at the same time.', examples: ['音楽を聞きながら勉強します。'] },
    { id: 'ba-yokatta', name: '～ばよかった', jp: '〜ばよかった', note: 'Regret: "I should have…".', examples: ['もっと勉強すればよかったです。'] },
  ]},
  { chapter: 19, book: 'Genki II', label: 'Meeting the Boss', points: [
    { id: 'honorific', name: 'Honorific verbs (尊敬語)', jp: '尊敬語', note: 'いらっしゃる・召し上がる・お～になる for others\' actions.', examples: ['先生はもうお帰りになりましたか。', '何を召し上がりますか。'] },
    { id: 'o-kudasai', name: 'お～ください', jp: 'お〜ください', note: 'Respectful request.', examples: ['こちらで少々お待ちください。'] },
    { id: 'te-kurete-arigatou', name: '～てくれてありがとう', jp: '〜てくれてありがとう', note: 'Thank someone for doing something.', examples: ['手伝ってくれてありがとう。'] },
    { id: 'te-yokatta', name: '～てよかったです', jp: '〜てよかった', note: '"I\'m glad that…".', examples: ['あなたに会えてよかったです。'] },
    { id: 'hazu', name: '～はずです', jp: '〜はず', note: '"Is supposed to / should be the case".', examples: ['彼は今日来るはずです。'] },
  ]},
  { chapter: 20, book: 'Genki II', label: 'Mary Goes Shopping', points: [
    { id: 'extra-modest', name: 'Extra-modest (おります etc.)', jp: '丁重語', note: 'おります・参ります・いたします — humble, very formal.', examples: ['三時までこちらにおります。'] },
    { id: 'humble-o-suru', name: 'Humble お～する', jp: 'お〜する', note: 'Humbly do something for someone: お持ちします.', examples: ['お荷物をお持ちします。'] },
    { id: 'naide', name: '～ないで', jp: '〜ないで', note: '"Without doing X".', examples: ['朝ご飯を食べないで学校に行きました。'] },
    { id: 'embedded-questions', name: 'Embedded questions (～か／かどうか)', jp: '〜かどうか', note: 'A question inside a sentence.', examples: ['田中さんが来るかどうか知りません。', '何時に始まるか教えてください。'] },
    { id: 'to-iu', name: 'XというY', jp: '〜という', note: '"X called/named Y".', examples: ['「七人の侍」という映画を見たことがありますか。'] },
    { id: 'yasui-nikui', name: '～やすい／～にくい', jp: '〜やすい/にくい', note: '"Easy to / hard to do".', examples: ['この本は読みやすいです。', 'この名前は覚えにくいです。'] },
  ]},
  { chapter: 21, book: 'Genki II', label: 'Burglar', points: [
    { id: 'passive', name: 'Passive (受け身)', jp: '受け身', note: 'Passive, often the "suffering" passive: 盗まれる・降られる.', examples: ['電車で足を踏まれました。', '雨に降られました。'] },
    { id: 'te-aru', name: '～てある', jp: '〜てある', note: 'Something has been done and remains so.', examples: ['ドアに名前が書いてあります。'] },
    { id: 'aida-ni', name: '～間に', jp: '〜間に', note: '"While/during X, Y happened".', examples: ['寝ている間に、雨が降りました。'] },
    { id: 'adjective-suru', name: 'Adjective＋する', jp: '〜くする', note: 'Make something X: 安くする・きれいにする.', examples: ['部屋をきれいにしました。'] },
    { id: 'te-hoshii', name: '～てほしい', jp: '〜てほしい', note: 'Want someone (else) to do something.', examples: ['父に早く帰ってきてほしいです。'] },
  ]},
  { chapter: 22, book: 'Genki II', label: 'Education in Japan', points: [
    { id: 'causative', name: 'Causative (使役)', jp: '使役', note: 'Make/let someone do: 行かせる・食べさせる.', examples: ['母は弟に野菜を食べさせました。'] },
    { id: 'causative-kudasai', name: 'Causative＋てください／てあげる', jp: '〜させてください', note: 'Ask to be allowed to do: 私に払わせてください.', examples: ['今日は私に払わせてください。'] },
    { id: 'nasai', name: 'Verb stem＋なさい', jp: '〜なさい', note: 'Firm command (parent/teacher tone).', examples: ['早く寝なさい。'] },
    { id: 'ba', name: '～ば conditional', jp: '〜ば', note: '"If": 行けば・安ければ・練習すれば.', examples: ['毎日練習すれば、上手になりますよ。'] },
    { id: 'noni', name: '～のに', jp: '〜のに', note: '"Although/despite" — often with frustration.', examples: ['たくさん勉強したのに、試験に落ちました。'] },
    { id: 'no-you-ni', name: '～のような／のように', jp: '〜のように', note: '"Like/as X".', examples: ['彼は魚のように泳げます。'] },
  ]},
  { chapter: 23, book: 'Genki II', label: 'Good-bye', points: [
    { id: 'causative-passive', name: 'Causative-passive', jp: '使役受け身', note: '"Be made to do": 待たされる・飲まされる.', examples: ['先輩にお酒を飲まされました。'] },
    { id: 'temo', name: '～ても', jp: '〜ても', note: '"Even if X".', examples: ['雨が降っても、行きます。'] },
    { id: 'koto-ni-suru', name: '～ことにする', jp: '〜ことにする', note: '"Decide to do".', examples: ['日本に留学することにしました。'] },
    { id: 'koto-ni-shite-iru', name: '～ことにしている', jp: '〜ことにしている', note: '"Make it a rule/habit to do".', examples: ['毎朝走ることにしています。'] },
    { id: 'made', name: '～まで (until)', jp: '〜まで', note: '"Until X happens".', examples: ['雨がやむまで、ここで待ちます。'] },
    { id: 'kata', name: 'Verb stem＋方', jp: '〜方', note: '"How to do X / way of doing".', examples: ['この漢字の読み方を教えてください。'] },
  ]},
];
